#!/bin/bash

# Discord Bot Daemon Setup Script for macOS
# This script sets up the bot to:
# 1. Run as a launchd daemon on startup
# 2. Automatically restart on crashes
# 3. Check for GitHub updates and restart when changes are detected
#
# Usage: Run this script from the bot directory, or pass the directory as an argument
#   ./setup-daemon.sh
#   ./setup-daemon.sh /path/to/bot

set -e

# Configuration - detect bot directory dynamically. BOT_DIR is the PROJECT ROOT (the git repo,
# holding kronk_config.yaml and all runtime state); the Python code lives in its src/ subdir.
if [ -n "$1" ]; then
    BOT_DIR="$(cd "$1" && pwd)"
elif [ -f "$(dirname "$0")/src/main.py" ]; then
    BOT_DIR="$(cd "$(dirname "$0")" && pwd)"
elif [ -f "./src/main.py" ]; then
    BOT_DIR="$(pwd)"
else
    echo "Error: Could not find src/main.py. Run this script from the bot directory or pass the path as an argument."
    exit 1
fi

# Generate a unique plist name based on directory name
BOT_NAME="$(basename "$BOT_DIR")"
PLIST_NAME="com.${USER}.${BOT_NAME}"
PLIST_PATH="$HOME/Library/LaunchAgents/${PLIST_NAME}.plist"
LOG_DIR="$BOT_DIR/logs"
UPDATE_CHECK_INTERVAL=300  # Check for updates every 5 minutes

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${GREEN}=== Discord Bot Daemon Setup ===${NC}"
echo "Bot directory: $BOT_DIR"
echo "Plist name: $PLIST_NAME"
echo ""

# Create LaunchAgents directory if it doesn't exist
mkdir -p "$HOME/Library/LaunchAgents"

# Create logs directory
mkdir -p "$LOG_DIR"

# Check for required tools
if ! command -v git &> /dev/null; then
    echo -e "${RED}Error: git is not installed${NC}"
    exit 1
fi

if ! command -v uv &> /dev/null; then
    echo -e "${YELLOW}Warning: uv is not installed. Installing via curl...${NC}"
    curl -LsSf https://astral.sh/uv/install.sh | sh
    export PATH="$HOME/.local/bin:$PATH"
fi

# Check if DISCORD_BOT_TOKEN is set
if [ -z "$DISCORD_BOT_TOKEN" ]; then
    echo -e "${YELLOW}Warning: DISCORD_BOT_TOKEN environment variable is not set.${NC}"
    echo "You'll need to set it in the plist file or export it before loading the daemon."
    read -p "Enter your DISCORD_BOT_TOKEN (or press Enter to skip): " TOKEN_INPUT
    if [ -n "$TOKEN_INPUT" ]; then
        DISCORD_BOT_TOKEN="$TOKEN_INPUT"
    fi
fi

# Optionally capture OLLAMA_API_KEY (needed for the web_search / web_fetch tools). launchd
# does not inherit your shell env, so it must be baked into the plist to reach the bot.
if [ -z "$OLLAMA_API_KEY" ]; then
    read -p "Enter your OLLAMA_API_KEY for web search (or press Enter to skip): " OLLAMA_KEY_INPUT
    if [ -n "$OLLAMA_KEY_INPUT" ]; then
        OLLAMA_API_KEY="$OLLAMA_KEY_INPUT"
    fi
fi

# Stop anything already running before rewriting the runner/plist. Re-running this script used
# to leave the OLD guard loop alive (it keeps executing the run-bot.sh it started with), so the
# new files had no effect until someone rebooted - and the stale loop happily restart-looped a
# bot it could no longer start. Setup is now idempotent: stop everything, rewrite, reload.
echo -e "${GREEN}Stopping any running daemon/bot for this directory...${NC}"
if [ -f "$PLIST_PATH" ]; then
    launchctl bootout "gui/$(id -u)/${PLIST_NAME}" 2>/dev/null \
        || launchctl unload "$PLIST_PATH" 2>/dev/null \
        || true
fi
pkill -f "${BOT_DIR}/run-bot.sh" 2>/dev/null || true
pkill -f "${BOT_DIR}/.bot-runner-active.sh" 2>/dev/null || true
for _py in python3 python; do
    for _entry in "src/main.py" "main.py"; do
        pkill -f "${BOT_DIR}/.venv/bin/${_py} ${_entry}" 2>/dev/null || true
    done
done
rm -f "$BOT_DIR/bot.pid" "$BOT_DIR/bot.heartbeat"
sleep 1

# Create the runner shim. The guard loop itself lives in scripts/bot-runner.sh (tracked in git,
# so it reaches the host on the next deploy); this shim only exists so the plist has a stable
# path to launch and never needs regenerating again.
echo -e "${GREEN}Creating bot runner shim...${NC}"
chmod +x "$BOT_DIR/scripts/bot-runner.sh" 2>/dev/null || true
cat > "$BOT_DIR/run-bot.sh" << 'RUNNER_EOF'
#!/bin/bash
# GENERATED by setup-daemon-mac.sh - do not edit, your changes will be overwritten.
# All guard-loop logic lives in scripts/bot-runner.sh (tracked in git so deploys update it).

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
RUNNER="$SCRIPT_DIR/scripts/bot-runner.sh"

if [ ! -f "$RUNNER" ]; then
    mkdir -p "$SCRIPT_DIR/logs"
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] FATAL: $RUNNER is missing - checkout is incomplete or predates it." \
        | tee -a "$SCRIPT_DIR/logs/bot.log"
    sleep 30   # don't let launchd KeepAlive hot-loop on a broken checkout
    exit 1
fi

exec /bin/bash "$RUNNER"
RUNNER_EOF

chmod +x "$BOT_DIR/run-bot.sh"

# Create the launchd plist
echo -e "${GREEN}Creating launchd plist...${NC}"

# Expand $HOME for the PATH in plist
EXPANDED_HOME="$HOME"

cat > "$PLIST_PATH" << PLIST_EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>${PLIST_NAME}</string>

    <key>ProgramArguments</key>
    <array>
        <string>/bin/bash</string>
        <string>${BOT_DIR}/run-bot.sh</string>
    </array>

    <key>WorkingDirectory</key>
    <string>${BOT_DIR}</string>

    <key>EnvironmentVariables</key>
    <dict>
        <key>PATH</key>
        <string>/usr/local/bin:/usr/bin:/bin:/opt/homebrew/bin:${EXPANDED_HOME}/.local/bin:${EXPANDED_HOME}/.cargo/bin</string>
        <key>HOME</key>
        <string>${EXPANDED_HOME}</string>
        <key>DISCORD_BOT_TOKEN</key>
        <string>${DISCORD_BOT_TOKEN:-YOUR_TOKEN_HERE}</string>
        <key>OLLAMA_API_KEY</key>
        <string>${OLLAMA_API_KEY:-}</string>
        <key>UPDATE_CHECK_INTERVAL</key>
        <string>${UPDATE_CHECK_INTERVAL}</string>
        <key>GIT_BRANCH</key>
        <string>main</string>
    </dict>

    <key>RunAtLoad</key>
    <true/>

    <key>KeepAlive</key>
    <dict>
        <key>SuccessfulExit</key>
        <false/>
    </dict>

    <key>StandardOutPath</key>
    <string>${LOG_DIR}/launchd-stdout.log</string>

    <key>StandardErrorPath</key>
    <string>${LOG_DIR}/launchd-stderr.log</string>

    <key>ProcessType</key>
    <string>Background</string>
</dict>
</plist>
PLIST_EOF

# Reload the daemon. The old flow ended here and told you to run `launchctl load` yourself,
# which is how a host could sit with a freshly written plist and a stale runner still running.
if [ -z "$DISCORD_BOT_TOKEN" ] || [ "$DISCORD_BOT_TOKEN" = "YOUR_TOKEN_HERE" ]; then
    echo ""
    echo -e "${RED}No DISCORD_BOT_TOKEN was provided - NOT starting the daemon.${NC}"
    echo "Edit the plist to add your token, then load it:"
    echo "   nano $PLIST_PATH      # replace YOUR_TOKEN_HERE"
    echo "   launchctl load $PLIST_PATH"
else
    echo -e "${GREEN}Loading the daemon...${NC}"
    if launchctl bootstrap "gui/$(id -u)" "$PLIST_PATH" 2>/dev/null || launchctl load "$PLIST_PATH" 2>/dev/null; then
        sleep 2
        if launchctl list | grep -q "$PLIST_NAME"; then
            echo -e "${GREEN}Daemon loaded and running.${NC}"
        else
            echo -e "${YELLOW}Daemon loaded but not showing in launchctl list - check the logs.${NC}"
        fi
    else
        echo -e "${RED}Could not load the daemon automatically. Load it by hand:${NC}"
        echo "   launchctl load $PLIST_PATH"
    fi
fi

echo ""
echo -e "${GREEN}Setup complete!${NC}"
echo ""
echo -e "${YELLOW}=== Useful commands ===${NC}"
echo "  Status:  launchctl list | grep $PLIST_NAME"
echo "  Logs:    tail -f $LOG_DIR/bot.log"
echo "  Stop:    ./kill-bot.py                     (or: launchctl unload $PLIST_PATH)"
echo "  Restart: launchctl kickstart -k gui/$(id -u)/${PLIST_NAME}"
echo ""
echo "The bot will now start on login, restart if it crashes or hangs, and pull GitHub"
echo "updates every ${UPDATE_CHECK_INTERVAL}s. Guard-loop changes ship with those updates"
echo "(scripts/bot-runner.sh is tracked in git), so this script only needs re-running if the"
echo "plist itself changes - e.g. a new token or a new environment variable."
