#!/bin/bash

# Bot guard loop - the process launchd keeps alive.
#
# This file is TRACKED IN GIT on purpose. It used to be generated by setup-daemon-mac.sh into
# an untracked ./run-bot.sh, which meant every change to the runner (new entry point, new
# health check) only reached the host if someone remembered to re-run the setup script there.
# That is exactly how the src/ move broke the deploy: the host kept running `python main.py`
# from a runner generated before the move. Now the runner ships with the code and updates
# itself on the next deploy.
#
# Self-update mechanism: bash reads a script lazily from disk, so overwriting this file while
# it runs can corrupt the running shell. On startup we copy ourselves to
# ./.bot-runner-active.sh and exec that copy, so the file bash is reading is never touched by
# git. After each successful update we compare the copy with the repo version and re-exec if
# they differ.
#
# Layering: launchd -> run-bot.sh (thin generated shim) -> this script -> uv run python src/main.py

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# When run from the repo (scripts/bot-runner.sh) the project root is one level up; when run as
# the active copy (./.bot-runner-active.sh) the script already sits in the project root.
if [ "$(basename "$SCRIPT_DIR")" = "scripts" ]; then
    BOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
else
    BOT_DIR="$SCRIPT_DIR"
fi

RUNNER_SOURCE="$BOT_DIR/scripts/bot-runner.sh"
RUNNER_ACTIVE="$BOT_DIR/.bot-runner-active.sh"
LOG_FILE="$BOT_DIR/logs/bot.log"
UPDATE_CHECK_INTERVAL="${UPDATE_CHECK_INTERVAL:-300}"   # how often to check git for updates
HEALTH_CHECK_INTERVAL="${HEALTH_CHECK_INTERVAL:-15}"    # how often to check the bot is alive+responsive
HEARTBEAT_FILE="$BOT_DIR/bot.heartbeat"                 # bot rewrites this every few seconds
HEARTBEAT_MAX_AGE="${HEARTBEAT_MAX_AGE:-90}"            # stale heartbeat older than this = hung -> restart
BRANCH="${GIT_BRANCH:-main}"

# Ensure logs directory exists
mkdir -p "$BOT_DIR/logs"

log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1" | tee -a "$LOG_FILE"
}

# Run from a private copy so a deploy can rewrite scripts/bot-runner.sh underneath us safely.
if [ "$BOT_RUNNER_ACTIVE" != "1" ]; then
    if [ -f "$RUNNER_SOURCE" ]; then
        cp "$RUNNER_SOURCE" "$RUNNER_ACTIVE" 2>/dev/null && chmod +x "$RUNNER_ACTIVE" 2>/dev/null
    fi
    if [ -x "$RUNNER_ACTIVE" ]; then
        exec env BOT_RUNNER_ACTIVE=1 /bin/bash "$RUNNER_ACTIVE"
    fi
    log "WARNING: could not create runner copy at $RUNNER_ACTIVE; running from source."
fi

# The bot entry point. Resolved fresh on every start so a restructure (main.py -> src/main.py)
# takes effect on the next restart instead of wedging the runner.
bot_entry() {
    if [ -f "$BOT_DIR/src/main.py" ]; then echo "src/main.py"; else echo "main.py"; fi
}

# Run a command with a hard timeout so a network stall (git fetch / uv sync) can never wedge
# the whole guard loop. Uses coreutils timeout/gtimeout when present, else a pure-bash fallback.
if command -v timeout >/dev/null 2>&1; then _TIMEOUT_BIN=timeout
elif command -v gtimeout >/dev/null 2>&1; then _TIMEOUT_BIN=gtimeout
else _TIMEOUT_BIN=""; fi

run_timeout() {
    local secs="$1"; shift
    if [ -n "$_TIMEOUT_BIN" ]; then
        "$_TIMEOUT_BIN" "$secs" "$@"
        return $?
    fi
    # Fallback: run in background, kill it if it overruns.
    "$@" &
    local cmd_pid=$!
    ( sleep "$secs"; kill -9 "$cmd_pid" 2>/dev/null ) &
    local killer=$!
    wait "$cmd_pid" 2>/dev/null
    local rc=$?
    kill "$killer" 2>/dev/null
    return $rc
}

# Seconds since the bot last wrote its heartbeat file (echoes a huge number if missing).
heartbeat_age() {
    if [ ! -f "$HEARTBEAT_FILE" ]; then echo 999999; return; fi
    local now hb
    now=$(date +%s)
    hb=$(stat -f %m "$HEARTBEAT_FILE" 2>/dev/null || stat -c %Y "$HEARTBEAT_FILE" 2>/dev/null)
    [ -z "$hb" ] && { echo 999999; return; }
    echo $(( now - hb ))
}

check_for_updates() {
    cd "$BOT_DIR"

    # Fetch latest changes from remote (bounded - a stalled fetch must not wedge the loop).
    if ! run_timeout 60 git fetch origin "$BRANCH" 2>/dev/null; then
        log "git fetch timed out or failed; will retry next cycle."
        return 1
    fi

    # Compare local and remote
    LOCAL=$(git rev-parse HEAD)
    REMOTE=$(git rev-parse "origin/$BRANCH")

    if [ "$LOCAL" != "$REMOTE" ]; then
        log "Update detected! Local: $LOCAL, Remote: $REMOTE"
        return 0
    fi
    return 1
}

pull_updates() {
    cd "$BOT_DIR"
    log "Applying latest changes (hard reset to origin/$BRANCH)..."
    # Hard reset instead of 'git pull': a dirty tree or diverged local commit can never block a
    # deploy/reset. Runtime files (heartbeat, pid, logs, config.yaml) are gitignored, so nothing
    # of value is discarded. This is what makes the 'push .deploy-trigger to force a reset' work
    # reliably every time.
    run_timeout 60 git fetch origin "$BRANCH" 2>/dev/null
    git reset --hard "origin/$BRANCH"

    # Reinstall dependencies if they changed in the new revision.
    if git diff HEAD@{1} HEAD --name-only 2>/dev/null | grep -q "pyproject.toml\|uv.lock"; then
        log "Dependencies changed, running uv sync..."
        run_timeout 300 uv sync
    fi
}

# If the deploy changed the runner itself, restart into the new version. Without this the host
# would keep running the old guard loop until someone re-ran setup-daemon-mac.sh by hand.
restart_if_runner_changed() {
    [ -f "$RUNNER_SOURCE" ] || return 0
    cmp -s "$RUNNER_SOURCE" "$RUNNER_ACTIVE" && return 0
    log "Runner script changed in this update - restarting the guard loop."
    stop_bot
    exec env -u BOT_RUNNER_ACTIVE /bin/bash "$RUNNER_SOURCE"
}

run_bot() {
    cd "$BOT_DIR"
    local entry
    entry="$(bot_entry)"
    log "Starting bot ($entry)..."

    # Remove any stale heartbeat from a previous run so the new process gets a clean grace
    # period (an absent heartbeat is treated as 'starting up', not 'hung') until it writes one.
    rm -f "$HEARTBEAT_FILE"

    # Run the bot using uv. Redirect straight to the log file (NO 'tee' pipe) so $! is the
    # uv/python pid, not a pipeline wrapper - otherwise stop_bot kills the wrong process and
    # orphaned bots pile up across restarts.
    uv run python "$entry" >> "$LOG_FILE" 2>&1 &
    BOT_PID=$!
    echo $BOT_PID > "$BOT_DIR/bot.pid"
    log "Bot started with PID: $BOT_PID"
}

stop_bot() {
    if [ -f "$BOT_DIR/bot.pid" ]; then
        PID=$(cat "$BOT_DIR/bot.pid")
        if kill -0 "$PID" 2>/dev/null; then
            log "Stopping bot (PID: $PID)..."
            kill "$PID" 2>/dev/null
            sleep 2
            if kill -0 "$PID" 2>/dev/null; then
                kill -9 "$PID" 2>/dev/null
            fi
        fi
        rm -f "$BOT_DIR/bot.pid"
    fi

    # Belt-and-braces: kill any bot python still running from THIS directory (catches orphans
    # left by earlier restarts, including ones started by a pre-src/ runner). Dir-specific via
    # the venv path, so other bots are untouched.
    local py entry
    for py in python3 python; do
        for entry in "src/main.py" "main.py"; do
            pkill -f "${BOT_DIR}/.venv/bin/${py} ${entry}" 2>/dev/null
        done
    done
    sleep 1
}

cleanup() {
    log "Received shutdown signal, cleaning up..."
    stop_bot
    exit 0
}

# Handle signals
trap cleanup SIGTERM SIGINT SIGHUP

# Main loop
log "=== Bot Runner Started ==="
log "Bot directory: $BOT_DIR"
log "Branch: $BRANCH"
log "Update check interval: ${UPDATE_CHECK_INTERVAL}s"

# True if the bot process is both alive AND responsive (heartbeat fresh).
bot_is_healthy() {
    # Dead / no pid file?
    if [ ! -f "$BOT_DIR/bot.pid" ]; then return 1; fi
    local pid
    pid=$(cat "$BOT_DIR/bot.pid")
    if ! kill -0 "$pid" 2>/dev/null; then
        log "Bot process (PID $pid) is not running."
        return 1
    fi
    # Alive but hung? Stale heartbeat means the event loop is wedged. Only judge staleness once
    # the bot has written a heartbeat at least once (fresh starts get a grace period until then).
    if [ -f "$HEARTBEAT_FILE" ]; then
        local age
        age=$(heartbeat_age)
        if [ "$age" -gt "$HEARTBEAT_MAX_AGE" ]; then
            log "Bot heartbeat stale (${age}s > ${HEARTBEAT_MAX_AGE}s) - loop is hung."
            return 1
        fi
    fi
    return 0
}

# Initial start
run_bot

# Guard loop: fast health checks (dead OR hung) on every tick; slower update checks.
SECONDS_SINCE_UPDATE_CHECK=0
while true; do
    sleep "$HEALTH_CHECK_INTERVAL"
    SECONDS_SINCE_UPDATE_CHECK=$((SECONDS_SINCE_UPDATE_CHECK + HEALTH_CHECK_INTERVAL))

    # 1) Health: restart a dead or hung bot immediately.
    if ! bot_is_healthy; then
        log "Bot unhealthy - restarting."
        stop_bot
        run_bot
        continue
    fi

    # 2) Updates: only every UPDATE_CHECK_INTERVAL seconds.
    if [ "$SECONDS_SINCE_UPDATE_CHECK" -ge "$UPDATE_CHECK_INTERVAL" ]; then
        SECONDS_SINCE_UPDATE_CHECK=0
        if check_for_updates; then
            stop_bot
            pull_updates
            restart_if_runner_changed   # execs away if the runner itself changed
            run_bot
        fi
    fi
done
